### ISSUE TITLE
How to fix this error? Thanks~

### ISSUE THREAD

**Issue by githublzb** [po0ya/csgan#2]
D:\TFCode\GAN\csgan-master>py -3 main.py --cfg experiments/cfgs/csgan/dcgan_mnist.yml --generate_A
Traceback (most recent call last):
  File "main.py", line 148, in <module>
    cfg = load_config(args.cfg)
  File "D:\TFCode\GAN\csgan-master\utils\config.py", line 113, in load_config
    if hasattr(flags, k.lower()):
  File "C:\Python35\lib\site-packages\tensorflow\python\platform\flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "C:\Python35\lib\site-packages\absl\flags\_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'cfg'. Did you mean: cfg_path ?

**Comment by winonama** [comment]
@githublzb do you fix this problem? i have same question
